

name: release-validate
on: [push, pull_request]

jobs:

  # macos:
  #   runs-on: macos-latest
  #   permissions:
  #     checks: write
  #     pull-requests: write
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
  #   - name: Download Love
  #     run: |
  #       curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.zip --url "https://api.github.com/repos/love2d/love/actions/artifacts/1348650151/zip"
  #       7z x love12.zip -o*
  #       7z x love12/love-macos.zip -o*
  #   - name: Run Builder
  #     env:
  #       LOVE_GRAPHICS_DEBUG: 1
  #     run: |
  #       ls
  #       love-macos/love.app/Contents/MacOS/love --version
  #       love-macos/love.app/Contents/MacOS/love main.lua example-project/main.lua --renderers opengl
  #   - name: Check Run
  #     run: |
  #       unzip example-project/dist/1.0.0/ExampleGame-macos.zip
  #       ExampleGame.app/Contents/MacOS/love
  #       exit 0

  windows:
    runs-on: windows-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Love
      run: |
        curl -L -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" --output love12.zip --url "https://api.github.com/repos/love2d/love/actions/artifacts/1348654247/zip"
        7z x love12.zip -o*
        7z x love12/love-12.0-win64.zip -o*
    - name: Run Builder
      run: powershell.exe ./love-12.0-win64/love-12.0-win64/lovec.exe ./main.lua ./example-project/main.lua
    