

name: release-validate
on: [push, pull_request]

jobs:

  build-love:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Builder
      run: curl -L https://github.com/ellraiser/love-build/releases/download/v0.3/love-build-0.3-macos.zip > love-build-0.3.zip
    - name: Extract Builder
      run: |
        unzip love-build-0.3.zip
    - name: Run Builder
      run: |
        ls
        open love-build.app --args example-project/main.lua
    - name: Check Run
      run: |
        unzip example-project/dist/1.0.0/ExampleGame-macos.zip
        chmod -R +x ExampleGame.app
        ExampleGame.app
        exit 0